"""
generate.py — POST /generate. Generate an ad creative for a product x segment.

Demo path NEVER hard-fails: live Bedrock when credentialed, otherwise an offline
"composed preview" — real product photo + grounded, segment-aware copy that the
frontend lays out into a finished ad. Copy streams as SSE; the image resolves
into a final event.

Inputs (body):
  - Catalog product:  {"product_id": "...", "segment_id": "..."}
  - Uploaded product: {"segment_id": "...", "product_name": "...",
                       "category": "...", "image_url": "<uploaded/data url>"}

Returned image semantics (honest framing for the UI):
  - source="live"  -> image_url is a NET-NEW image generated by Bedrock.
  - source="preview" -> image_url is null; the frontend composes the ad over
                        `product_image_url` (the real product photo / upload).

Two entrypoints:
  generate_summary(body)  -> dict (non-streaming summary, used by tests + /predict pairing)
  generate_events(body)   -> generator of SSE event dicts: {event, data}
"""
import json
import time

from core import data, cache, perf_model, prompts, bedrock, copywriter, imagegen


def _resolve_plan(body):
    """Load product (catalog or uploaded) + segment, mine best features, decide format.

    Returns (product, segment, best, fmt, uploaded: bool).
    `product` always has at least name/category/description and image_url.
    """
    segment_id = body.get("segment_id")
    segment = data.get_segment(segment_id)
    if not segment:
        raise ValueError("unknown segment_id")

    product_id = body.get("product_id")
    if product_id:
        product = data.get_product(product_id)
        if not product:
            raise ValueError("unknown product_id")
        uploaded = False
    else:
        # Uploaded / ad-hoc product — described inline by the user.
        name = (body.get("product_name") or "Your product").strip() or "Your product"
        slug = "".join(c if c.isalnum() else "-" for c in name.lower()).strip("-")[:32] or "item"
        product = {
            "id": f"upload-{slug}",
            "name": name,
            "category": body.get("category", "tops"),
            "description": body.get("description", name),
            "tags": [],
            "image_url": body.get("image_url"),  # uploaded data URL or path
        }
        uploaded = True

    best = perf_model.best_features_for_segment(segment_id)
    fmt = best["format"] or segment.get("top_format", "social_square")
    return product, segment, best, fmt, uploaded


def _prediction(segment_id, fmt, best):
    return perf_model.predict(segment_id, fmt, best["image_style"], best["copy_tone"])


def _offline_copy(product, segment, fmt, best, uploaded):
    """Best offline copy: hand-authored manifest entry for catalog items, else
    the segment-aware template writer (which also covers uploaded products)."""
    if not uploaded:
        cached = cache.get(product["id"], segment["id"])
        if cached and cached.get("copy"):
            return cached["copy"]
    return copywriter.write_copy(product, segment, fmt, best["copy_tone"])


def generate_summary(body):
    """Non-streaming: full creative. Live copy/image if credentialed, else preview."""
    product, segment, best, fmt, uploaded = _resolve_plan(body)
    pred = _prediction(segment["id"], fmt, best)

    copy = None
    source = "preview"
    image_url = None                       # net-new generated image
    product_image_url = product.get("image_url")  # reference (real photo / upload)

    if bedrock.available():
        try:
            sys_p = prompts.copy_system_prompt()
            usr_p = prompts.copy_user_prompt(product, segment, fmt, best["copy_tone"])
            raw = bedrock.generate_copy(sys_p, usr_p)
            copy = _parse_copy(raw)
            source = "live"
        except bedrock.BedrockUnavailable:
            copy = None
    if copy is None:
        copy = _offline_copy(product, segment, fmt, best, uploaded)

    # Net-new AI image. Bedrock (Nova Canvas) when live; else keyless text-to-image.
    if bedrock.available():
        try:
            from core import storage
            w, h = prompts.FORMAT_DIMS.get(fmt, (1024, 1024))
            png = bedrock.generate_image(prompts.image_prompt(product, segment, best["image_style"], fmt), w, h)
            image_url = storage.save_image(product["id"], segment["id"], png)
            source = "live"
        except Exception:  # noqa: BLE001
            image_url = None
    if image_url is None:
        image_url = imagegen.generate(product, segment, fmt)
        source = "generated" if image_url else "preview"

    return {
        "product_id": product["id"],
        "segment_id": segment["id"],
        "format": fmt,
        "copy": copy,
        "image_url": image_url,
        "product_image_url": product_image_url,
        "source": source,
        "image_style": best["image_style"],
        "copy_tone": best["copy_tone"],
        "brand_tokens_applied": prompts.brand_tokens_applied(segment),
        "prediction": pred,
        "uploaded": uploaded,
    }


def _parse_copy(raw):
    """Extract {headline, body, cta} JSON from Claude output (tolerant of fencing/prose)."""
    raw = raw.strip()
    start, end = raw.find("{"), raw.rfind("}")
    if start != -1 and end != -1:
        try:
            obj = json.loads(raw[start:end + 1])
            return {"headline": obj.get("headline", ""),
                    "body": obj.get("body", ""),
                    "cta": obj.get("cta", "Shop now")}
        except json.JSONDecodeError:
            pass
    return {"headline": raw[:60], "body": raw[:160], "cta": "Shop now"}


def generate_events(body):
    """
    SSE generator. Emits:
      meta   -> {format, image_style, copy_tone, brand_tokens_applied, prediction,
                 source, product_image_url, uploaded}
      delta  -> {text}   (copy typed in, token-ish chunks)
      copy   -> {copy}   (final structured copy)
      image  -> {image_url}   (net-new live image, or null for preview)
      done   -> {source, elapsed_ms}
    Copy streams first, image resolves last. Never throws on the demo path.
    """
    t0 = time.time()
    try:
        product, segment, best, fmt, uploaded = _resolve_plan(body)
    except ValueError as e:
        yield {"event": "error", "data": {"error": str(e)}}
        return

    pred = _prediction(segment["id"], fmt, best)
    product_image_url = product.get("image_url")

    live = bedrock.available()
    source = "live" if live else "preview"

    yield {"event": "meta", "data": {
        "product_id": product["id"], "segment_id": segment["id"], "format": fmt,
        "image_style": best["image_style"], "copy_tone": best["copy_tone"],
        "brand_tokens_applied": prompts.brand_tokens_applied(segment),
        "prediction": pred, "source": source,
        "product_image_url": product_image_url, "uploaded": uploaded,
    }}

    # --- COPY ---
    streamed_copy = ""
    copy_obj = None
    if live:
        try:
            sys_p = prompts.copy_system_prompt()
            usr_p = prompts.copy_user_prompt(product, segment, fmt, best["copy_tone"])
            for delta in bedrock.stream_copy(sys_p, usr_p):
                streamed_copy += delta
                yield {"event": "delta", "data": {"text": delta}}
            copy_obj = _parse_copy(streamed_copy)
            yield {"event": "copy", "data": {"copy": copy_obj}}
        except bedrock.BedrockUnavailable:
            live = False
            source = "preview"

    if copy_obj is None:
        # Offline copy — type it in word-by-word so UX is identical to live.
        copy_obj = _offline_copy(product, segment, fmt, best, uploaded)
        typed = f"{copy_obj['headline']}\n\n{copy_obj['body']}"
        for word in typed.split(" "):
            yield {"event": "delta", "data": {"text": word + " "}}
            time.sleep(0.012)  # gentle typing cadence; keeps the demo lively
        yield {"event": "copy", "data": {"copy": copy_obj}}

    # --- IMAGE (net-new) ---
    image_url = None
    if live:
        try:
            from core import storage  # local-only image persistence
            w, h = prompts.FORMAT_DIMS.get(fmt, (1024, 1024))
            img_prompt = prompts.image_prompt(product, segment, best["image_style"], fmt)
            png = bedrock.generate_image(img_prompt, w, h)
            image_url = storage.save_image(product["id"], segment["id"], png)
            source = "live"
        except Exception:  # noqa: BLE001 — keep live copy, try the open generator
            image_url = None
    if image_url is None:
        # Keyless text-to-image: a genuinely NEW image, generated at the ad's
        # aspect ratio (cached -> instant on repeat). Falls back to compose-over-photo.
        image_url = imagegen.generate(product, segment, fmt)
        source = "generated" if image_url else "preview"

    yield {"event": "image", "data": {"image_url": image_url,
                                      "product_image_url": product_image_url,
                                      "source": source}}
    yield {"event": "done", "data": {"source": source,
                                     "elapsed_ms": int((time.time() - t0) * 1000)}}


def lambda_handler(event, context):
    body = json.loads(event.get("body") or "{}")
    return {"statusCode": 200,
            "headers": {"Content-Type": "application/json", "Access-Control-Allow-Origin": "*"},
            "body": json.dumps(generate_summary(body))}
