import { type Copy, type Prediction } from "../lib/api";
import { BRAND } from "../theme";
import AdCreative from "./AdCreative";
import PredictedCtrBadge from "./PredictedCtrBadge";

interface Props {
  baseImageUrl: string | null;   // generated (live) OR product/upload photo
  segmentId: string | null;
  segmentName?: string;
  channel?: string;
  streamingText: string;
  copy: Copy | null;
  format: string | null;
  prediction: Prediction | null;
  generating: boolean;
  source: string | null;         // "live" | "preview"
  brandTokens: string[];
}

export default function CreativeCard(p: Props) {
  return (
    <div className="flex flex-col gap-4">
      <div className="rounded-3xl bg-panel shadow-card overflow-hidden border border-stone/10 p-3 md:p-4">
        <div className="relative">
          <AdCreative
            baseImageUrl={p.baseImageUrl}
            segmentId={p.segmentId}
            channel={p.channel}
            format={p.format}
            copy={p.copy}
            streamingText={p.streamingText}
            generating={p.generating}
            source={p.source}
            brandName={BRAND.name}
          />
          {p.source && p.baseImageUrl && (
            <span className="absolute -top-1 left-1 z-10 bg-panel/90 text-ink text-[10px] uppercase tracking-wider px-2 py-1 rounded-full shadow">
              {p.source === "live" ? "● live Bedrock · net-new image"
                : p.source === "generated" ? "● AI-generated image"
                : "● composed preview"}
            </span>
          )}
        </div>

        {/* Generation provenance — what the engine decided + why (honest framing). */}
        {(p.brandTokens?.length > 0 || p.format) && (
          <div className="mt-3 flex items-center gap-2 flex-wrap px-1">
            {p.brandTokens?.map((t) => (
              <span key={t} className="text-[10px] uppercase tracking-wider bg-sand text-stone px-2 py-1 rounded-full">{t}</span>
            ))}
            {p.source === "preview" && (
              <span className="text-[10px] text-stone/80 italic">
                Copy + layout composed locally · live image generator was unreachable, showing the product photo
              </span>
            )}
            {p.source === "generated" && (
              <span className="text-[10px] text-stone/80 italic">
                New image generated by AI from the product + segment · grounded copy + data-predicted CTR
              </span>
            )}
          </div>
        )}
      </div>

      <PredictedCtrBadge pred={p.prediction} segmentId={p.segmentId} />
    </div>
  );
}
